/**
 * stats.ts — Statistical decision-support engine for crash games.
 *
 * Crash outcomes generated by a provably-fair RNG are independent events.
 * This module summarises historical frequencies, estimates conditional
 * probabilities, and recommends risk-aware cashout targets.
 * None of its outputs guarantees a win.
 *
 * STABLE v4 — balanced (usable signals, not ultra-conservative paralysis):
 *  - Regime / momentum / recovery kept as telemetry + soft target caps
 *  - Ensemble drives masterSignal but DANGER only on true danger
 *  - WAIT still allows BET with lower targets
 *  - Prefer mid targets 1.35–2.00x; swing 2–3x when form is hot
 *  - No 85% hit-rate clamp that forced 1.10x forever
 *  - INSTANT boundary 1.15; hard max cashout 3.00x
 */

export type CrashTier = 'INSTANT' | 'LOW' | 'MED' | 'HIGH';
export type MasterSignal = 'STRONG_BUY' | 'BUY' | 'WAIT' | 'DANGER' | 'ABORT';
export type SessionMomentum = 'cold' | 'neutral' | 'hot';
export type VolatilityRegime = 'LOW' | 'NORMAL' | 'HIGH' | 'EXTREME';
export type RecoveryMode = 'NONE' | 'POST_MEGA' | 'POST_SPIKE' | 'COLD_LOCK';
export type RecentMomentumLabel = 'cold' | 'neutral' | 'hot' | 'unstable';

export interface VolatilityRegimeInfo {
  regime: VolatilityRegime;
  score: number;
  description: string;
  recentStdDev: number;
  recentCv: number;
  recentWindow: number;
}

export interface EnsembleBreakdown {
  markov: number;
  streak: number;
  form: number;
  regime: number;
}

type TierPercentages = Record<CrashTier, number>;
type MarkovMatrix = Record<CrashTier, TierPercentages>;

export interface TargetLevel {
  target: number;
  hitCount: number;
  hitRate: number;
  recentHitRate: number;
  signal: 'SAFE' | 'OK' | 'RISKY' | 'RARE';
  lastHitAgo: number;
  longestGap: number;
  ev: number;
  mathProb: number;
}

export interface PatternMatch {
  patternName: string;
  occurrences: number;
  nextRoundWinRates: { target: number; hitRate: number }[];
  p90?: number;
  p80?: number;
  p50?: number;
}

export interface TimePatternMatch {
  minute: number;
  occurrences: number;
  p90: number;
  p80: number;
  p50: number;
  hitRates: { target: number; hitRate: number }[];
}

export interface SequenceMatch {
  sequence: string[];
  occurrences: number;
  pInstantNext: number;
  pSafeNext: number;
  pMedNext: number;
  pHighNext: number;
  p90: number;
  p80: number;
  p50: number;
}

export interface CrashStats {
  count: number;
  mean: number;
  median: number;
  stdDev: number;
  min: number;
  max: number;

  pUnder2: number;
  p2to5: number;
  pOver5: number;
  pInstantCrash: number;

  targets: TargetLevel[];

  p99SafeCashout: number;
  p95SafeCashout: number;
  p90SafeCashout: number;
  p80SafeCashout: number;
  p70SafeCashout: number;
  p65SafeCashout: number;
  p60SafeCashout: number;
  p50SafeCashout: number;

  ema: number;

  currentLowStreak: number;
  currentHighStreak: number;
  currentHighStreak250: number;
  longestLowStreak: number;

  recentMean: number;
  olderMean: number;
  trend: 'rising' | 'falling' | 'flat';

  suggestedCashout: number;
  suggestedCashoutWinRate: number;
  conservativeCashout: number;
  aggressiveCashout: number;
  cashoutReason: string;

  riskScore: number;
  riskLabel: 'LOW' | 'MEDIUM' | 'HIGH';
  confidence: number;
  volatility: 'low' | 'normal' | 'high';
  volatilityPct: number;
  q3: number;

  /** Recent-window regime (preferred over full-history volatility for decisions). */
  volatilityRegime: VolatilityRegime;
  volatilityRegimeInfo: VolatilityRegimeInfo;

  /** Weighted last-15 form (-100 cold … +100 hot). */
  recentMomentumScore: number;
  recentMomentumLabel: RecentMomentumLabel;

  /** Cooldown state after mega / spike / long cold. */
  recoveryMode: RecoveryMode;

  /** Ensemble 0–100 (higher = safer entry for conservative engine). */
  ensembleScore: number;
  ensembleBreakdown: EnsembleBreakdown;

  detectedPatterns: PatternMatch[];
  timePattern?: TimePatternMatch;
  sequenceMatch?: SequenceMatch;

  // Legacy aliases retained for API/UI compatibility.
  instant_crash_risk?: number;
  instant_crash_warning?: string;
  recentOutcomes: number[];

  // Markov-chain output.
  markovMatrix: MarkovMatrix;
  markovNext: TierPercentages;
  markovSuggestedCashout: number;

  // Five-round session momentum.
  sessionDanger: boolean;
  sessionHot: boolean;
  sessionMomentum: SessionMomentum;

  // Composite decision output.
  masterSignal: MasterSignal;
  signalConfidence: number;

  // Instant-cluster model.
  instantClusterRisk: number;
  instantCrashWarning: string;

  stabilityAnalysis?: {
    similarity_score: number;
    stability_index: number;
    status: 'STABLE' | 'CAUTION' | 'VOLATILE' | 'INSUFFICIENT_DATA';
    matched_patterns_count: number;
    historical_win_rate_1_5x: number;
    holdScore?: number;
    holdReasons?: string[];
    holdSignal?: boolean;
  };
}

export interface BetTimeData {
  isLKSleep?: boolean;
  currentLKTimeStr?: string;
  lkPhase?: 'SLEEP' | 'MORNING' | 'DAY' | 'EVENING' | 'PRIME' | 'LATE' | string;
}

export interface BetSignal {
  should_bet: boolean;
  skip_reason: string | null;
  strategy: string;
  cashout_target: number;
  recommended_bet_units: number;
  swing_target: number | null;
  volatility_phase: 'CALM' | 'NORMAL' | 'VOLATILE';
  recommended_stake_pct: number;
  strategy_reason?: string;
  holdScore: number;
  holdReasons: string[];
  holdSignal: boolean;
}

interface NormalizedRound {
  crash_point: number;
  created_at: string;
  timestamp: number;
}

// ─── Constants ────────────────────────────────────────────────────────────────

const TIERS: readonly CrashTier[] = ['INSTANT', 'LOW', 'MED', 'HIGH'];
const TARGET_LEVELS = [
  1.05, 1.1, 1.18, 1.2, 1.5, 1.8, 2, 3, 5, 10, 15, 20, 25,
] as const;

/** Absolute maximum any signal will ever output (customer requirement). */
const SIGNAL_MAX_CASHOUT = 3.00;
/** Conservative default anchor — hits ~65% of rounds at 97% RTP. */
const SIGNAL_DEFAULT_TARGET = 1.50;
/** Cold-streak cap: when 3+ of last 5 rounds are below 2x. */
const COLD_STREAK_CAP = 1.35;
/** Minimum signalConfidence required to issue a BET (not SKIP). */
const MIN_CONFIDENCE_TO_BET = 25;

const ZERO_TIERS: TierPercentages = { INSTANT: 0, LOW: 0, MED: 0, HIGH: 0 };

// ─── Pure helpers ─────────────────────────────────────────────────────────────

const round1 = (v: number): number => Math.round(v * 10) / 10;
const round2 = (v: number): number => Math.round(v * 100) / 100;
const clamp = (v: number, lo: number, hi: number): number => Math.min(hi, Math.max(lo, v));

function meanOf(values: readonly number[], fallback = 0): number {
  return values.length === 0
    ? fallback
    : values.reduce((s, v) => s + v, 0) / values.length;
}

/**
 * STABLE v2: INSTANT boundary raised to 1.15 (was 1.10).
 * Rounds between 1.10–1.14 were previously misclassified as INSTANT,
 * inflating cluster-risk scores and causing spurious ABORT signals.
 */
function tierOf(v: number): CrashTier {
  if (v < 1.15) return 'INSTANT';
  if (v < 2.00) return 'LOW';
  if (v < 5.00) return 'MED';
  return 'HIGH';
}

function normalizeRounds(
  raw: { crash_point: number; created_at: string }[],
): NormalizedRound[] {
  const seen = new Set<string>();
  const out: NormalizedRound[] = [];
  for (const r of raw) {
    const v = Number(r.crash_point);
    const t = Date.parse(r.created_at);
    if (!Number.isFinite(v) || v < 1 || !Number.isFinite(t)) continue;
    const key = `${t}|${v}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push({ crash_point: v, created_at: r.created_at, timestamp: t });
  }
  return out.sort((a, b) => b.timestamp - a.timestamp);
}

function percentagesFromCounts(counts: Record<CrashTier, number>): TierPercentages {
  const total = TIERS.reduce((s, t) => s + counts[t], 0);
  if (total === 0) return { ...ZERO_TIERS };
  const result: TierPercentages = {
    INSTANT: round1((counts.INSTANT / total) * 100),
    LOW:     round1((counts.LOW     / total) * 100),
    MED:     round1((counts.MED     / total) * 100),
    HIGH:    round1((counts.HIGH    / total) * 100),
  };
  const sum = TIERS.reduce((s, t) => s + result[t], 0);
  const largest = TIERS.reduce((b, t) => counts[t] > counts[b] ? t : b);
  result[largest] = round1(result[largest] + (100 - sum));
  return result;
}

function buildMarkov(values: readonly number[]): {
  matrix: MarkovMatrix;
  next: TierPercentages;
  suggestedCashout: number;
  currentStateTransitions: number;
} {
  const counts: Record<CrashTier, Record<CrashTier, number>> = {
    INSTANT: { INSTANT: 0, LOW: 0, MED: 0, HIGH: 0 },
    LOW:     { INSTANT: 0, LOW: 0, MED: 0, HIGH: 0 },
    MED:     { INSTANT: 0, LOW: 0, MED: 0, HIGH: 0 },
    HIGH:    { INSTANT: 0, LOW: 0, MED: 0, HIGH: 0 },
  };
  const globalCounts: Record<CrashTier, number> = { ...ZERO_TIERS };
  const chron = [...values].reverse();
  for (const v of chron) globalCounts[tierOf(v)] += 1;
  for (let i = 0; i < chron.length - 1; i++) {
    counts[tierOf(chron[i])][tierOf(chron[i + 1])] += 1;
  }
  const fallback = percentagesFromCounts(globalCounts);
  const matrix = {} as MarkovMatrix;
  for (const from of TIERS) {
    const rowTotal = TIERS.reduce((s, to) => s + counts[from][to], 0);
    matrix[from] = rowTotal > 0 ? percentagesFromCounts(counts[from]) : { ...fallback };
  }
  const currentTier = values.length > 0 ? tierOf(values[0]) : 'LOW';
  const next = { ...matrix[currentTier] };
  const currentStateTransitions = TIERS.reduce((s, to) => s + counts[currentTier][to], 0);
  // Conservative Markov cashout suggestions (capped at SIGNAL_MAX_CASHOUT)
  const cashouts: Record<CrashTier, number> = {
    INSTANT: 1.10,
    LOW:     1.35,
    MED:     2.00,
    HIGH:    2.50,
  };
  const mostLikely = TIERS.reduce((b, t) => next[t] > next[b] ? t : b);
  return { matrix, next, suggestedCashout: cashouts[mostLikely], currentStateTransitions };
}

function cashoutAtWinRate(sortedAsc: readonly number[], targetPct: number): number {
  if (sortedAsc.length === 0) return 1.05;
  const q = clamp(1 - targetPct / 100, 0, 1);
  const idx = Math.floor(q * (sortedAsc.length - 1));
  return round2(sortedAsc[idx]);
}

function percentileFromOutcomes(outcomes: readonly number[], targetPct: number): number {
  return clamp(
    cashoutAtWinRate([...outcomes].sort((a, b) => a - b), targetPct),
    1.01, 30,
  );
}

function countLeading(values: readonly number[], pred: (v: number) => boolean): number {
  let c = 0;
  for (const v of values) { if (!pred(v)) break; c++; }
  return c;
}

function longestRun(values: readonly number[], pred: (v: number) => boolean): number {
  let longest = 0, cur = 0;
  for (const v of [...values].reverse()) {
    if (pred(v)) { cur++; longest = Math.max(longest, cur); } else { cur = 0; }
  }
  return longest;
}

function recencyWeight(i: number): number {
  if (i < 5) return 3;
  if (i < 15) return 2;
  if (i < 30) return 1.5;
  return 1;
}

function mapLinear(x: number, x0: number, x1: number): number {
  if (x1 <= x0) return 0;
  return clamp(((x - x0) / (x1 - x0)) * 100, 0, 100);
}

function tierRisk(v: number): number {
  const t = tierOf(v);
  if (t === 'INSTANT') return 100;
  if (t === 'LOW') return 65;
  if (t === 'MED') return 25;
  return 8;
}

/**
 * STABLE v2: doubling only fires when ≥ 2 INSTANT rounds appear in the
 * last-5 window (was: any single INSTANT in position 0 doubled the score).
 */
function computeInstantClusterRisk(values: readonly number[]): number {
  if (values.length === 0) return 0;
  let clusterWindows = 0, windows = 0;
  for (let start = 0; start + 5 <= values.length; start++) {
    windows++;
    const cnt = values.slice(start, start + 5).filter(v => tierOf(v) === 'INSTANT').length;
    if (cnt >= 2) clusterWindows++;
  }
  const historicalRate = windows > 0
    ? (clusterWindows / windows) * 100
    : (values.filter(v => tierOf(v) === 'INSTANT').length / values.length) * 100;
  const recentInstants = values.slice(0, 5).filter(v => tierOf(v) === 'INSTANT').length;
  const recentPressure = clamp((recentInstants / 2) * 100, 0, 100);
  let risk = historicalRate * 0.7 + recentPressure * 0.3;
  // Only double when there are 2+ instants in the most recent 5 rounds
  if (recentInstants >= 2) risk *= 2;
  return Math.round(clamp(risk, 0, 100));
}

const REGIME_WINDOW = 40;
const REGIME_MIN_N = 15;

/**
 * Classify recent market condition using last ~40 rounds (not full history).
 * Conservative: easier to enter HIGH/EXTREME after megas or heavy instants.
 */
export function detectVolatilityRegime(values: readonly number[]): VolatilityRegimeInfo {
  const W = Math.min(REGIME_WINDOW, values.length);
  if (W < REGIME_MIN_N) {
    return {
      regime: 'NORMAL',
      score: 50,
      description: 'Insufficient recent rounds for regime detection.',
      recentStdDev: 0,
      recentCv: 0,
      recentWindow: W,
    };
  }

  const window = values.slice(0, W);
  const mean = meanOf(window);
  const recentStdDev = Math.sqrt(meanOf(window.map(v => (v - mean) ** 2)));
  const recentCv = mean > 0 ? recentStdDev / mean : 0;

  const megaInWindow = window.filter(v => v >= 10).length;
  const megaInLast10 = values.slice(0, Math.min(10, values.length)).filter(v => v >= 10).length;
  const instantPct = (window.filter(v => v < 1.15).length / W) * 100;
  const lowStreak = countLeading(values, v => v < 2);
  const highStreak250 = countLeading(values, v => v >= 2.5);

  const cvComp = mapLinear(recentCv, 0.35, 1.6);
  const stdComp = mapLinear(recentStdDev, 1.0, 6.0);
  const megaComp = clamp(megaInWindow * 18 + megaInLast10 * 12, 0, 100);
  const instantComp = mapLinear(instantPct, 5, 35);
  const streakComp = clamp(lowStreak * 12 + (highStreak250 >= 4 ? 25 : 0), 0, 100);
  const pressureComp = clamp(megaComp * 0.55 + instantComp * 0.45, 0, 100);

  const score = Math.round(clamp(
    cvComp * 0.40 + stdComp * 0.25 + pressureComp * 0.20 + streakComp * 0.15,
    0, 100,
  ));

  let regime: VolatilityRegime;
  if (score >= 75) regime = 'EXTREME';
  else if (score >= 50) regime = 'HIGH';
  else if (score >= 25) regime = 'NORMAL';
  else regime = 'LOW';

  // Conservative overrides after megas
  if (values.slice(0, 3).some(v => v >= 10) && regime === 'LOW') {
    regime = 'HIGH';
  }
  if (values[0] >= 10 && score < 75) {
    regime = score >= 50 ? 'EXTREME' : 'HIGH';
  }

  const description =
    regime === 'EXTREME' ? 'Extreme recent volatility — prefer SKIP / ultra-safe targets.'
    : regime === 'HIGH' ? 'Elevated volatility — lower targets and stricter entry.'
    : regime === 'LOW' ? 'Calm recent window — still use risk gates.'
    : 'Normal variance — baseline conservative rules.';

  return {
    regime,
    score,
    description,
    recentStdDev: round2(recentStdDev),
    recentCv: round2(recentCv),
    recentWindow: W,
  };
}

function computeRecentMomentum(values: readonly number[]): {
  score: number;
  label: RecentMomentumLabel;
} {
  const n = Math.min(15, values.length);
  if (n === 0) return { score: 0, label: 'neutral' };

  let weighted = 0;
  let wSum = 0;
  for (let i = 0; i < n; i++) {
    const w = n - i; // newest heaviest
    const v = values[i];
    let s: number;
    if (v < 1.15) s = -100;
    else if (v < 2) s = -35;
    else if (v < 5) s = 40;
    else if (v < 10) s = 55;
    else s = 20; // mega: muted — not pure "hot for betting"
    weighted += s * w;
    wSum += w;
  }
  const score = Math.round(clamp(weighted / wSum, -100, 100));

  const slice = values.slice(0, n);
  const instants = slice.filter(v => v < 1.15).length;
  const highs = slice.filter(v => v >= 5).length;
  if (instants >= 3 && highs >= 2) {
    return { score, label: 'unstable' };
  }
  if (score <= -25) return { score, label: 'cold' };
  if (score >= 25) return { score, label: 'hot' };
  return { score, label: 'neutral' };
}

function detectRecoveryMode(values: readonly number[]): RecoveryMode {
  if (values.length === 0) return 'NONE';
  if (values[0] >= 10) return 'POST_MEGA';
  if (values.slice(0, 3).some(v => v >= 10)) return 'POST_SPIKE';
  if (countLeading(values, v => v < 2) >= 4) return 'COLD_LOCK';
  if (countLeading(values, v => v >= 2.5) >= 5) return 'POST_SPIKE';
  return 'NONE';
}

function computeEnsembleSignal(args: {
  markovNext: TierPercentages;
  currentLowStreak: number;
  currentInstantStreak: number;
  momentumScore: number;
  momentumLabel: RecentMomentumLabel;
  regime: VolatilityRegime;
  recoveryMode: RecoveryMode;
  riskScore: number;
}): { score: number; components: EnsembleBreakdown; recommendation: MasterSignal } {
  const {
    markovNext, currentLowStreak, currentInstantStreak, momentumScore,
    momentumLabel, regime, recoveryMode, riskScore,
  } = args;

  const markov = clamp(
    (markovNext.MED + markovNext.HIGH) - markovNext.INSTANT * 1.2,
    0, 100,
  );

  let streak = 60;
  streak -= currentLowStreak * 6;
  streak -= currentInstantStreak * 14;
  if (recoveryMode === 'POST_MEGA') streak -= 20;
  if (recoveryMode === 'POST_SPIKE') streak -= 10;
  if (recoveryMode === 'COLD_LOCK') streak -= 12;
  streak = clamp(streak, 0, 100);

  let form = clamp((momentumScore + 100) / 2, 0, 100);
  if (momentumLabel === 'unstable') form = Math.min(form, 40);

  const regimeMap: Record<VolatilityRegime, number> = {
    LOW: 78, NORMAL: 65, HIGH: 45, EXTREME: 25,
  };
  const regimeScore = regimeMap[regime];

  const score = Math.round(clamp(
    markov * 0.30 + streak * 0.25 + form * 0.25 + regimeScore * 0.20,
    0, 100,
  ));

  // v4 balanced: DANGER only for true danger; recovery/cold → WAIT (lower targets), not auto-SKIP
  const isPostMega = recoveryMode === 'POST_MEGA';
  const isClear = recoveryMode === 'NONE';

  let recommendation: MasterSignal = 'WAIT';
  if (riskScore >= 85 || currentInstantStreak >= 3 || (regime === 'EXTREME' && score < 30)) {
    recommendation = 'ABORT';
  } else if (riskScore >= 75 || isPostMega || currentInstantStreak >= 2) {
    recommendation = 'DANGER';
  } else if (
    score >= 58
    && (regime === 'LOW' || regime === 'NORMAL')
    && isClear
    && momentumLabel !== 'unstable'
    && riskScore < 45
  ) {
    recommendation = score >= 72 ? 'STRONG_BUY' : 'BUY';
  } else if (score >= 48 && riskScore < 65 && isClear) {
    recommendation = 'BUY';
  } else if (score >= 48 && riskScore < 60 && !isPostMega) {
    // POST_SPIKE / COLD_LOCK: still allow BUY when ensemble ok
    recommendation = 'BUY';
  } else {
    recommendation = 'WAIT';
  }

  // EXTREME: no STRONG_BUY; BUY only if ensemble still strong
  if (regime === 'EXTREME') {
    if (recommendation === 'STRONG_BUY') recommendation = 'WAIT';
    else if (recommendation === 'BUY' && score < 55) recommendation = 'WAIT';
  }

  return {
    score,
    components: {
      markov: round1(markov),
      streak: round1(streak),
      form: round1(form),
      regime: regimeScore,
    },
    recommendation,
  };
}

/**
 * Soft hit-rate bias only under HIGH risk. Desired ~70% (not 85%) so targets stay usable.
 * Fail-safe 1.20x rather than permanently pinning 1.10x.
 */
function preferHighHitTarget(stats: CrashStats, desiredHitRate: number): number {
  const base = stats.suggestedCashout;
  const candidates = stats.targets
    .filter(t => t.target <= base + 1e-9 && t.hitRate >= desiredHitRate)
    .sort((a, b) => b.target - a.target);
  if (candidates[0]) return candidates[0].target;
  return Math.max(1.20, Math.min(base, 1.35));
}

function analyzeSequence(values: readonly number[]): SequenceMatch | undefined {
  if (values.length < 5) return undefined;
  for (let len = 4; len >= 2; len--) {
    const current = values.slice(0, len).reverse().map(tierOf);
    const outcomes: number[] = [];
    for (let ni = 1; ni + len <= values.length; ni++) {
      const hist = values.slice(ni, ni + len).reverse().map(tierOf);
      if (hist.every((t, i) => t === current[i])) outcomes.push(values[ni - 1]);
    }
    if (outcomes.length > 0) {
      return {
        sequence: current,
        occurrences: outcomes.length,
        pInstantNext: Math.round((outcomes.filter(v => tierOf(v) === 'INSTANT').length / outcomes.length) * 100),
        pSafeNext:    Math.round((outcomes.filter(v => v >= 1.15).length / outcomes.length) * 100),
        pMedNext:     Math.round((outcomes.filter(v => v >= 2).length  / outcomes.length) * 100),
        pHighNext:    Math.round((outcomes.filter(v => v >= 5).length  / outcomes.length) * 100),
        p90: percentileFromOutcomes(outcomes, 90),
        p80: percentileFromOutcomes(outcomes, 80),
        p50: percentileFromOutcomes(outcomes, 50),
      };
    }
  }
  return undefined;
}

function analyzeCurrentStreak(
  values: readonly number[],
  streakLen: number,
  kind: 'low' | 'high',
): PatternMatch | undefined {
  if (streakLen === 0) return undefined;
  const matches = (v: number) => kind === 'low' ? v < 2 : v >= 2;
  const outcomes: number[] = [];
  for (let ni = 0; ni + streakLen < values.length; ni++) {
    let ok = true;
    for (let off = 1; off <= streakLen; off++) {
      if (!matches(values[ni + off])) { ok = false; break; }
    }
    if (ok) outcomes.push(values[ni]);
  }
  if (outcomes.length === 0) return undefined;
  return {
    patternName: `${streakLen} consecutive ${kind} crashes`,
    occurrences: outcomes.length,
    nextRoundWinRates: [1.2, 1.5, 2, 3, 5].map(t => ({
      target: t,
      hitRate: Math.round((outcomes.filter(o => o >= t).length / outcomes.length) * 100),
    })),
    p90: percentileFromOutcomes(outcomes, 90),
    p80: percentileFromOutcomes(outcomes, 80),
    p50: percentileFromOutcomes(outcomes, 50),
  };
}

function analyzeMinutePattern(rounds: readonly NormalizedRound[]): TimePatternMatch | undefined {
  if (rounds.length === 0) return undefined;
  const minute = new Date(rounds[0].timestamp).getUTCMinutes();
  const outcomes = rounds
    .filter(r => new Date(r.timestamp).getUTCMinutes() === minute)
    .map(r => r.crash_point);
  if (outcomes.length < 10) return undefined;
  return {
    minute,
    occurrences: outcomes.length,
    p90: percentileFromOutcomes(outcomes, 90),
    p80: percentileFromOutcomes(outcomes, 80),
    p50: percentileFromOutcomes(outcomes, 50),
    hitRates: [1.2, 1.5, 2, 3, 5].map(t => ({
      target: t,
      hitRate: Math.round((outcomes.filter(o => o >= t).length / outcomes.length) * 100),
    })),
  };
}

// ─── Main computation ─────────────────────────────────────────────────────────

export function computeStats(
  rawRounds: { crash_point: number; created_at: string }[],
): CrashStats {
  const rounds = normalizeRounds(rawRounds);
  if (rounds.length === 0) return emptyStats();

  const values = rounds.map(r => r.crash_point);
  const sorted = [...values].sort((a, b) => a - b);
  const n = values.length;
  const mean = meanOf(values);
  const median = n % 2 === 0
    ? (sorted[n / 2 - 1] + sorted[n / 2]) / 2
    : sorted[Math.floor(n / 2)];
  const stdDev = Math.sqrt(meanOf(values.map(v => (v - mean) ** 2)));
  const min = sorted[0];
  const max = sorted[n - 1];

  const pUnder2       = Math.round((values.filter(v => v < 2).length / n) * 100);
  const p2to5         = Math.round((values.filter(v => v >= 2 && v < 5).length / n) * 100);
  const pOver5        = Math.round((values.filter(v => v >= 5).length / n) * 100);
  const pInstantCrash = round1((values.filter(v => v < 1.15).length / n) * 100);

  const recent20 = values.slice(0, 20);
  const targets: TargetLevel[] = TARGET_LEVELS.map(target => {
    const hitCount = values.filter(v => v >= target).length;
    const hitRate = Math.round((hitCount / n) * 100);
    const recentHitRate = Math.round(
      (recent20.filter(v => v >= target).length / recent20.length) * 100,
    );
    const lastHitAgo = values.findIndex(v => v >= target);
    let longestGap = 0, gap = 0;
    for (const v of [...values].reverse()) {
      if (v >= target) { longestGap = Math.max(longestGap, gap); gap = 0; } else { gap++; }
    }
    longestGap = Math.max(longestGap, gap);
    const signal: TargetLevel['signal'] =
      hitRate >= 80 ? 'SAFE' : hitRate >= 55 ? 'OK' : hitRate >= 25 ? 'RISKY' : 'RARE';
    return {
      target, hitCount, hitRate, recentHitRate, signal, lastHitAgo, longestGap,
      ev: round2((hitRate / 100) * target - 1),
      mathProb: round1((0.97 / target) * 100),
    };
  });

  const p99SafeCashout = cashoutAtWinRate(sorted, 99);
  const p95SafeCashout = cashoutAtWinRate(sorted, 95);
  const p90SafeCashout = cashoutAtWinRate(sorted, 90);
  const p80SafeCashout = cashoutAtWinRate(sorted, 80);
  const p70SafeCashout = cashoutAtWinRate(sorted, 70);
  const p65SafeCashout = cashoutAtWinRate(sorted, 65);
  const p60SafeCashout = cashoutAtWinRate(sorted, 60);
  const p50SafeCashout = round2(median);

  // EMA (exponential moving average, 20-period, newest first)
  const chron = [...values].reverse();
  const span = Math.min(20, n);
  const alpha = 2 / (span + 1);
  let ema = chron[0];
  for (let i = 1; i < chron.length; i++) ema = alpha * chron[i] + (1 - alpha) * ema;
  ema = round2(ema);

  const currentLowStreak  = countLeading(values, v => v < 2);
  const currentHighStreak = countLeading(values, v => v >= 2);
  const currentHighStreak250 = countLeading(values, v => v >= 2.50);
  const currentInstantStreak = countLeading(values, v => tierOf(v) === 'INSTANT');
  const longestLowStreak  = longestRun(values, v => v < 2);

  const recent5  = values.slice(0, 5);
  const older10  = values.slice(5, 15);
  const recentMean = meanOf(recent5, mean);
  const olderMean  = meanOf(older10, mean);
  let trend: CrashStats['trend'] = 'flat';
  if (recentMean > olderMean * 1.2) trend = 'rising';
  else if (recentMean < olderMean * 0.8) trend = 'falling';

  const cvRatio = mean > 0 ? stdDev / mean : 0;
  const volatilityPct = round1(cvRatio * 100);
  const q3 = sorted[Math.min(n - 1, Math.floor((n - 1) * 0.75))];
  const volatility: CrashStats['volatility'] =
    cvRatio > 1.2 ? 'high' : cvRatio < 0.5 ? 'low' : 'normal';

  const coldCount = recent5.filter(v => v < 2).length;
  const hotCount  = recent5.filter(v => v >= 2).length;
  const sessionDanger = recent5.length >= 3 && coldCount >= 3;
  const sessionHot    = recent5.length >= 3 && hotCount  >= 3;
  const sessionMomentum: SessionMomentum = sessionDanger ? 'cold' : sessionHot ? 'hot' : 'neutral';

  const volatilityRegimeInfo = detectVolatilityRegime(values);
  const momentum = computeRecentMomentum(values);
  const recoveryMode = detectRecoveryMode(values);

  let weightedRiskTotal = 0, totalWeight = 0;
  values.forEach((v, i) => {
    const w = recencyWeight(i);
    weightedRiskTotal += tierRisk(v) * w;
    totalWeight += w;
  });
  let riskScore = totalWeight > 0 ? weightedRiskTotal / totalWeight : 50;
  if (sessionDanger) riskScore += 12;
  if (sessionHot)    riskScore -= 15;
  if (trend === 'falling') riskScore += 5;
  if (trend === 'rising')  riskScore -= 5;
  if (currentInstantStreak >= 2) riskScore += 12;
  if (volatilityRegimeInfo.regime === 'HIGH') riskScore += 6;
  if (volatilityRegimeInfo.regime === 'EXTREME') riskScore += 12;
  if (recoveryMode === 'POST_MEGA') riskScore += 10;
  if (recoveryMode === 'COLD_LOCK') riskScore += 6;
  if (momentum.label === 'unstable') riskScore += 6;
  riskScore = Math.round(clamp(riskScore, 0, 100));

  const riskLabel: CrashStats['riskLabel'] =
    riskScore >= 60 ? 'HIGH' : riskScore >= 35 ? 'MEDIUM' : 'LOW';

  const markov = buildMarkov(values);
  const favorableMarkov = markov.next.MED + markov.next.HIGH;

  const ensemble = computeEnsembleSignal({
    markovNext: markov.next,
    currentLowStreak,
    currentInstantStreak,
    momentumScore: momentum.score,
    momentumLabel: momentum.label,
    regime: volatilityRegimeInfo.regime,
    recoveryMode,
    riskScore,
  });
  const masterSignal = ensemble.recommendation;

  const instantClusterRisk = computeInstantClusterRisk(values);
  const instantCrashWarning = instantClusterRisk > 60
    ? `High instant-crash cluster risk (${instantClusterRisk}%): avoid aggressive targets.`
    : 'No elevated instant-crash cluster detected.';

  const sampleStrength      = clamp(Math.sqrt(n / 200) * 100, 0, 100);
  const markovDominance     = Math.max(...TIERS.map(t => markov.next[t]));
  const transitionStrength  = clamp(Math.sqrt(markov.currentStateTransitions / 30) * 100, 0, 100);
  const momentumStrength    = recent5.length < 5
    ? (recent5.length / 5) * 50
    : Math.abs(hotCount - coldCount) * 20;
  let signalConfidence = Math.round(clamp(
    sampleStrength    * 0.45
    + markovDominance * 0.20
    + transitionStrength * 0.25
    + momentumStrength   * 0.10,
    0, 100,
  ));
  // Mild confidence cuts only — keep values usable/varying for AI display
  if (volatilityRegimeInfo.regime === 'HIGH') {
    signalConfidence = Math.round(signalConfidence * 0.90);
  }
  if (volatilityRegimeInfo.regime === 'EXTREME') {
    signalConfidence = Math.round(signalConfidence * 0.80);
  }
  if (momentum.label === 'unstable') signalConfidence -= 8;
  if (recoveryMode === 'POST_MEGA') signalConfidence -= 8;
  signalConfidence = Math.round(clamp(signalConfidence, 0, 100));
  const confidence = Math.min(100, Math.round((n / 50) * 100));

  const winRateAt = (t: number) =>
    Math.round((values.filter(v => v >= t).length / n) * 100);

  // ─── Balanced cashout ladder (v4) ─────────────────────────────────────────
  const cashoutReasons: string[] = [];
  let suggestedCashout = 1.80;

  if (riskScore >= 80 || currentLowStreak >= 5 || currentInstantStreak >= 2) {
    suggestedCashout = 1.20;
    cashoutReasons.push(`selected 1.20x (elevated floor: risk ${riskScore}, lowStreak ${currentLowStreak})`);
  } else if (riskScore >= 70 || currentLowStreak >= 4) {
    suggestedCashout = 1.35;
    cashoutReasons.push(`selected 1.35x (high risk caution: risk ${riskScore})`);
  } else if (riskScore >= 55 || currentLowStreak >= 3 || favorableMarkov < 40) {
    suggestedCashout = 1.50;
    cashoutReasons.push(`selected 1.50x (medium caution: risk ${riskScore}, Markov MED+HIGH ${favorableMarkov.toFixed(0)}%)`);
  } else if (riskScore >= 40 || favorableMarkov < 50) {
    suggestedCashout = 1.80;
    cashoutReasons.push(`selected 1.80x (balanced baseline)`);
  } else if (riskScore < 25 && momentum.label === 'hot') {
    suggestedCashout = clamp(p60SafeCashout, 2.20, 2.50);
    cashoutReasons.push(`selected ${suggestedCashout.toFixed(2)}x (hot form + low risk)`);
  } else if (riskScore < 35) {
    suggestedCashout = clamp(p65SafeCashout, 2.00, 2.35);
    cashoutReasons.push(`selected ${suggestedCashout.toFixed(2)}x (stable low-risk band)`);
  } else {
    suggestedCashout = clamp(p70SafeCashout, 1.80, 2.15);
    cashoutReasons.push(`selected ${suggestedCashout.toFixed(2)}x (p70 band)`);
  }

  const regimeCap: Record<VolatilityRegime, number> = {
    LOW: SIGNAL_MAX_CASHOUT,
    NORMAL: 2.50,
    HIGH: 2.00,
    EXTREME: 1.50,
  };
  let cap = regimeCap[volatilityRegimeInfo.regime];
  // POST_MEGA: one-round caution, not permanent 1.10 lock
  if (recoveryMode === 'POST_MEGA') cap = Math.min(cap, 1.50);
  if (recoveryMode === 'POST_SPIKE') cap = Math.min(cap, 1.80);
  if (recoveryMode === 'COLD_LOCK') cap = Math.min(cap, 1.50);
  if (momentum.label === 'unstable') cap = Math.min(cap, 1.80);
  if (suggestedCashout > cap) {
    cashoutReasons.push(`regime/recovery cap ${cap.toFixed(2)}x (${volatilityRegimeInfo.regime}, ${recoveryMode})`);
    suggestedCashout = cap;
  }
  suggestedCashout = round2(clamp(suggestedCashout, 1.15, SIGNAL_MAX_CASHOUT));

  const conservativeCashout = suggestedCashout;
  const aggressiveCashout   = round2(clamp(Math.max(suggestedCashout * 1.35, 2.20), 1.50, SIGNAL_MAX_CASHOUT));

  const sequenceMatch    = analyzeSequence(values);
  const detectedPatterns: PatternMatch[] = [];
  const lowPattern  = analyzeCurrentStreak(values, currentLowStreak,  'low');
  const highPattern = analyzeCurrentStreak(values, currentHighStreak, 'high');
  if (lowPattern)  detectedPatterns.push(lowPattern);
  if (highPattern) detectedPatterns.push(highPattern);
  const timePattern = analyzeMinutePattern(rounds);

  return {
    count: n,
    mean: round2(mean),
    median: round2(median),
    stdDev: round2(stdDev),
    min: round2(min),
    max: round2(max),
    pUnder2, p2to5, pOver5, pInstantCrash,
    targets,
    p99SafeCashout, p95SafeCashout, p90SafeCashout,
    p80SafeCashout, p70SafeCashout, p65SafeCashout, p60SafeCashout, p50SafeCashout,
    ema,
    currentLowStreak, currentHighStreak, currentHighStreak250, longestLowStreak,
    recentMean: round2(recentMean),
    olderMean:  round2(olderMean),
    trend,
    suggestedCashout,
    suggestedCashoutWinRate: winRateAt(suggestedCashout),
    conservativeCashout,
    aggressiveCashout,
    cashoutReason: `${cashoutReasons.join('; ')}. Regime ${volatilityRegimeInfo.regime}. Final target: ${suggestedCashout.toFixed(2)}x.`,
    riskScore, riskLabel, confidence, volatility, volatilityPct,
    q3: round2(q3),
    volatilityRegime: volatilityRegimeInfo.regime,
    volatilityRegimeInfo,
    recentMomentumScore: momentum.score,
    recentMomentumLabel: momentum.label,
    recoveryMode,
    ensembleScore: ensemble.score,
    ensembleBreakdown: ensemble.components,
    detectedPatterns,
    ...(timePattern    ? { timePattern }    : {}),
    ...(sequenceMatch  ? { sequenceMatch }  : {}),
    instant_crash_risk:    instantClusterRisk,
    instant_crash_warning: instantCrashWarning,
    recentOutcomes:  values.slice(0, 10),
    markovMatrix:    markov.matrix,
    markovNext:      markov.next,
    markovSuggestedCashout: markov.suggestedCashout,
    sessionDanger, sessionHot, sessionMomentum,
    masterSignal, signalConfidence,
    instantClusterRisk, instantCrashWarning,
  };
}

function emptyStats(): CrashStats {
  const emptyTargets: TargetLevel[] = TARGET_LEVELS.map(target => ({
    target, hitCount: 0, hitRate: 0, recentHitRate: 0,
    signal: 'RARE', lastHitAgo: -1, longestGap: 0,
    ev: -1, mathProb: round1((0.97 / target) * 100),
  }));
  const zeroMatrix: MarkovMatrix = {
    INSTANT: { ...ZERO_TIERS },
    LOW:     { ...ZERO_TIERS },
    MED:     { ...ZERO_TIERS },
    HIGH:    { ...ZERO_TIERS },
  };
  return {
    count: 0, mean: 0, median: 0, stdDev: 0, min: 0, max: 0,
    pUnder2: 0, p2to5: 0, pOver5: 0, pInstantCrash: 0,
    targets: emptyTargets,
    p99SafeCashout: 1.05, p95SafeCashout: 1.05, p90SafeCashout: 1.10,
    p80SafeCashout: 1.20, p70SafeCashout: 1.50, p65SafeCashout: 1.65, p60SafeCashout: 1.80, p50SafeCashout: 2.00,
    ema: 0,
    currentLowStreak: 0, currentHighStreak: 0, currentHighStreak250: 0, longestLowStreak: 0,
    recentMean: 0, olderMean: 0, trend: 'flat',
    suggestedCashout: 1.05, suggestedCashoutWinRate: 0,
    conservativeCashout: 1.10, aggressiveCashout: 1.50,
    cashoutReason: 'No valid rounds available; using the 1.05x safety floor.',
    riskScore: 50, riskLabel: 'MEDIUM', confidence: 0,
    volatility: 'normal', volatilityPct: 0, q3: 0,
    volatilityRegime: 'NORMAL',
    volatilityRegimeInfo: {
      regime: 'NORMAL',
      score: 50,
      description: 'Insufficient data.',
      recentStdDev: 0,
      recentCv: 0,
      recentWindow: 0,
    },
    recentMomentumScore: 0,
    recentMomentumLabel: 'neutral',
    recoveryMode: 'NONE',
    ensembleScore: 50,
    ensembleBreakdown: { markov: 0, streak: 0, form: 50, regime: 60 },
    detectedPatterns: [],
    instant_crash_risk: 0, instant_crash_warning: 'Insufficient data.',
    recentOutcomes: [],
    markovMatrix: zeroMatrix, markovNext: { ...ZERO_TIERS }, markovSuggestedCashout: 1.05,
    sessionDanger: false, sessionHot: false, sessionMomentum: 'neutral',
    masterSignal: 'WAIT', signalConfidence: 0,
    instantClusterRisk: 0, instantCrashWarning: 'Insufficient data.',
  };
}

export function gradePrediction(
  risk: 'LOW' | 'MEDIUM' | 'HIGH',
  actualCrash: number,
  cashoutTarget?: number | null,
): boolean {
  if (cashoutTarget !== null && cashoutTarget !== undefined && cashoutTarget > 1) {
    return actualCrash >= cashoutTarget;
  }
  if (risk === 'LOW') return actualCrash >= 2;
  if (risk === 'MEDIUM') return actualCrash >= 1.5 && actualCrash < 4;
  return actualCrash < 1.5;
}

/** Allow swing targets when form is good — not only ultra-rare LOW+rising. */
function allowSwing(stats: CrashStats): boolean {
  const regime = stats.volatilityRegime ?? 'NORMAL';
  const buyish = stats.masterSignal === 'BUY' || stats.masterSignal === 'STRONG_BUY';
  const hotForm = stats.sessionHot || stats.recentMomentumLabel === 'hot';
  return (
    buyish
    && hotForm
    && (stats.recoveryMode ?? 'NONE') === 'NONE'
    && regime !== 'EXTREME'
    && stats.riskScore < 55
  );
}

export function computeBetSignal(
  stats: CrashStats,
  gameType: '1xbet' | 'aviator' | 'luckyjet' = '1xbet',
  timeData?: BetTimeData,
): BetSignal {
  const regime: VolatilityRegime = stats.volatilityRegime ?? 'NORMAL';
  let volatility_phase: BetSignal['volatility_phase'] = 'NORMAL';
  if (regime === 'LOW') volatility_phase = 'CALM';
  else if (regime === 'HIGH' || regime === 'EXTREME') volatility_phase = 'VOLATILE';

  // ─── Hold Score (v4: no double-stack mega + regime pile-on) ───────────────
  let holdScore = 0;
  const holdReasons: string[] = [];
  const outcomes = stats.recentOutcomes || [];

  if (stats.currentHighStreak250 >= 6) {
    holdScore += 30;
    holdReasons.push(`High streak cooldown (+30): ${stats.currentHighStreak250} rounds >= 2.50x`);
  }

  // Single mega rule: last round mega OR (if not) mega in last 3
  if (outcomes.length >= 1 && outcomes[0] >= 10.0) {
    holdScore += 35;
    holdReasons.push(`Mega round cooldown (+35): previous ${outcomes[0]}x`);
  } else if (outcomes.slice(0, 3).some(v => v >= 10)) {
    holdScore += 20;
    holdReasons.push('Mega in last 3 rounds (+20)');
  }

  if (outcomes.length >= 1 && outcomes[0] < 1.15 && stats.riskScore >= 55) {
    holdScore += 20;
    holdReasons.push(`Instant follow-up (+20): prev ${outcomes[0]}x`);
  }

  if (stats.currentLowStreak >= 6) {
    holdScore += 20;
    holdReasons.push(`Extended cold streak ${stats.currentLowStreak} (+20)`);
  }

  if (regime === 'EXTREME') {
    holdScore += 15;
    holdReasons.push('EXTREME regime (+15)');
  }

  holdScore = Math.min(100, Math.max(0, holdScore));
  const holdThreshold = 58;
  const holdSignal = holdScore >= holdThreshold;

  const skipReasons: string[] = [];

  if (timeData?.isLKSleep) {
    skipReasons.push(`Colombo sleep phase (${timeData.currentLKTimeStr || ''})`);
  }

  // Hard SKIP only for true danger (WAIT still allows BET with lower target)
  if (stats.masterSignal === 'ABORT' || stats.masterSignal === 'DANGER') {
    skipReasons.push(`Market volatility: ${stats.masterSignal}`);
  }

  // Soft confidence gate — only EXTREME raises bar slightly
  const minConf = regime === 'EXTREME' ? 30 : MIN_CONFIDENCE_TO_BET;
  if (stats.signalConfidence < minConf) {
    skipReasons.push(`Confidence ${stats.signalConfidence} < ${minConf} gate`);
  }

  if (holdSignal) {
    skipReasons.push(`Pattern Risk threshold (${holdScore}/${holdThreshold}): ${holdReasons.join('; ')}`);
  }

  let partnerModifier = 1.0;
  if (gameType === 'aviator') {
    partnerModifier = 0.92;
    if (stats.instantClusterRisk > 60) {
      skipReasons.push('Aviator: severe cluster risk (>60%)');
    }
  } else if (gameType === 'luckyjet') {
    partnerModifier = 1.05;
    if (stats.currentLowStreak >= 4 && stats.instantClusterRisk > 60) {
      skipReasons.push('LuckyJet: severe low streak cluster lock');
    }
  }

  if (skipReasons.length > 0) {
    return {
      should_bet: false,
      skip_reason: skipReasons.join(' | '),
      strategy: 'SKIP',
      cashout_target: 0,
      recommended_bet_units: 0,
      swing_target: null,
      volatility_phase,
      recommended_stake_pct: 0,
      strategy_reason: `[v4-balanced] ${stats.cashoutReason}`,
      holdScore,
      holdReasons,
      holdSignal,
    };
  }

  const phase = timeData?.lkPhase ?? 'DAY';
  const phaseMax: Record<string, number> = {
    SLEEP:   1.20,
    MORNING: 2.50,
    DAY:     2.50,
    EVENING: 3.00,
    PRIME:   3.00,
    LATE:    2.50,
  };
  const maxByPhase = (phaseMax[phase] ?? 2.50) * partnerModifier;

  let cashoutTarget = clamp(stats.suggestedCashout * partnerModifier, 1.15, maxByPhase);

  // Soft stress caps (not 1.10 floor)
  if (stats.recoveryMode === 'POST_MEGA') {
    cashoutTarget = Math.min(cashoutTarget, 1.50);
  } else if (volatility_phase === 'VOLATILE') {
    cashoutTarget = Math.min(cashoutTarget, 2.00);
  }

  // Soft hit-rate bias only when risk is HIGH (desired ~70%)
  if (stats.riskLabel === 'HIGH') {
    cashoutTarget = Math.min(cashoutTarget, preferHighHitTarget(stats, 70));
  }

  // Aggressive floor on STRONG_BUY
  if (stats.masterSignal === 'STRONG_BUY') {
    cashoutTarget = Math.max(cashoutTarget, 1.80);
  }

  cashoutTarget = round2(clamp(cashoutTarget, 1.15, SIGNAL_MAX_CASHOUT));

  const aggressive = stats.masterSignal === 'STRONG_BUY';
  const stake = aggressive ? 3 : stats.masterSignal === 'BUY' ? 2 : 1;

  const swingTarget = (allowSwing(stats) && maxByPhase >= 2.0)
    ? round2(Math.min(Math.max(stats.aggressiveCashout, 2.20), maxByPhase, SIGNAL_MAX_CASHOUT))
    : null;

  const strategyLabel = aggressive
    ? 'AGGRESSIVE'
    : stats.masterSignal === 'WAIT'
      ? 'CONSERVATIVE'
      : 'CONSERVATIVE';

  return {
    should_bet: true,
    skip_reason: null,
    strategy: strategyLabel,
    cashout_target: cashoutTarget,
    recommended_bet_units: aggressive ? 1.5 : 1,
    swing_target: swingTarget,
    volatility_phase,
    recommended_stake_pct: volatility_phase === 'VOLATILE' ? Math.min(1.5, stake) : stake,
    strategy_reason: `[v4-balanced] ${stats.masterSignal} conf=${stats.signalConfidence}% ensemble=${stats.ensembleScore} regime=${regime}. ${stats.cashoutReason}`,
    holdScore,
    holdReasons,
    holdSignal,
  };
}

/**
 * Always-populated Safe / Swing / Moon tiers for DB + UI.
 * On SKIP, cashout_target stays 0 for grading, but tiers remain advisory.
 */
export function buildAdvisoryTiers(
  stats: CrashStats,
  betSignal: BetSignal,
): { tier_safe: number; tier_swing: number; tier_moon: number } {
  const safeBase = betSignal.should_bet && betSignal.cashout_target > 0
    ? betSignal.cashout_target
    : Math.max(1.20, stats.suggestedCashout || stats.conservativeCashout || 1.50);

  const tier_safe = round2(clamp(safeBase, 1.15, SIGNAL_MAX_CASHOUT));

  const swingRaw = betSignal.swing_target
    ?? Math.max(stats.aggressiveCashout || 2.2, tier_safe * 1.35);
  const tier_swing = round2(clamp(Math.max(tier_safe, swingRaw), 1.15, SIGNAL_MAX_CASHOUT));

  const moonRaw = Math.max(
    tier_swing,
    stats.p50SafeCashout || 2.0,
    stats.p60SafeCashout || 2.2,
  );
  const tier_moon = round2(clamp(moonRaw, tier_swing, SIGNAL_MAX_CASHOUT));

  return { tier_safe, tier_swing, tier_moon };
}

export function buildHumanSummary(
  stats: CrashStats,
  betSignal: BetSignal,
): string {
  const regime = stats.volatilityRegime ?? 'NORMAL';
  const ensemble = stats.ensembleScore ?? 0;
  const recovery = stats.recoveryMode ?? 'NONE';
  if (!betSignal.should_bet) {
    return `${stats.masterSignal}: ${betSignal.skip_reason ?? 'risk controls blocked entry'}. Regime ${regime}, ensemble ${ensemble}, recovery ${recovery}. ${stats.instantCrashWarning}`;
  }
  const favorableMarkov = round1(stats.markovNext.MED + stats.markovNext.HIGH);
  return `${stats.masterSignal} (${stats.signalConfidence}% conf): regime ${regime}, ensemble ${ensemble}, ${stats.sessionMomentum} momentum, risk ${stats.riskScore}/100, Markov MED+HIGH=${favorableMarkov}%. Target ${betSignal.cashout_target.toFixed(2)}x (hist hit ~${stats.suggestedCashoutWinRate}%). Stake ${betSignal.recommended_stake_pct}% bankroll.`;
}

export function analyzeStability(
  currentRounds: { crash_point: number }[],
  historicalRounds: { crash_point: number }[]
) {
  if (currentRounds.length < 5 || historicalRounds.length < 10) {
    return {
      similarity_score: 0,
      stability_index: 0,
      status: 'INSUFFICIENT_DATA' as const,
      matched_patterns_count: 0,
      historical_win_rate_1_5x: 0,
      sample_size: historicalRounds.length
    };
  }

  // Local helper to match routes logic
  const getLocalTier = (v: number) => {
    if (v < 1.15) return 'INSTANT';
    if (v < 2.00) return 'LOW';
    if (v < 5.00) return 'MED';
    return 'HIGH';
  };

  const activePattern = currentRounds.slice(0, 5).reverse().map(r => getLocalTier(Number(r.crash_point)));
  const histChron = [...historicalRounds].reverse().map(r => ({
    crash_point: Number(r.crash_point)
  }));

  let matchedSegments = 0;
  let stableFollowCount = 0;
  let instantFollowCount = 0;
  const bestMatches: number[] = [];

  for (let i = 0; i <= histChron.length - 6; i++) {
    const segment = histChron.slice(i, i + 5).map(r => getLocalTier(r.crash_point));
    let matchingElements = 0;
    for (let j = 0; j < 5; j++) {
      if (segment[j] === activePattern[j]) {
        matchingElements++;
      }
    }
    const windowSim = (matchingElements / 5) * 100;
    bestMatches.push(windowSim);

    if (matchingElements >= 3) {
      matchedSegments++;
      const nextRound = histChron[i + 5];
      if (nextRound) {
        if (nextRound.crash_point >= 1.50) stableFollowCount++;
        if (nextRound.crash_point < 1.15) instantFollowCount++;
      }
    }
  }

  bestMatches.sort((a, b) => b - a);
  const topMatches = bestMatches.slice(0, 5);
  const avgSimilarity = topMatches.length > 0
    ? Math.round(topMatches.reduce((s, v) => s + v, 0) / topMatches.length)
    : 0;

  const historical_win_rate_1_5x = matchedSegments > 0
    ? Math.round((stableFollowCount / matchedSegments) * 100)
    : 0;
  const historical_instant_rate = matchedSegments > 0
    ? Math.round((instantFollowCount / matchedSegments) * 100)
    : 0;

  const stability_index = matchedSegments > 0
    ? Math.max(0, Math.min(100, Math.round(historical_win_rate_1_5x - (historical_instant_rate * 1.5))))
    : 50;

  let status: 'STABLE' | 'CAUTION' | 'VOLATILE' | 'INSUFFICIENT_DATA' = 'CAUTION';
  if (matchedSegments < 3) {
    status = 'INSUFFICIENT_DATA';
  } else if (stability_index >= 70) {
    status = 'STABLE';
  } else if (stability_index < 45) {
    status = 'VOLATILE';
  }

  return {
    similarity_score: avgSimilarity,
    stability_index: stability_index,
    status,
    matched_patterns_count: matchedSegments,
    historical_win_rate_1_5x: historical_win_rate_1_5x,
    sample_size: historicalRounds.length
  };
}
