/**
 * stats.ts - Statistical decision-support engine for crash games.
 *
 * Crash outcomes generated by a provably-fair RNG are not truly predictable.
 * This module summarizes historical behavior, estimates conditional frequencies,
 * and recommends risk-aware cashout targets. None of its outputs guarantees a win.
 */

export type CrashTier = 'INSTANT' | 'LOW' | 'MED' | 'HIGH';
export type MasterSignal = 'STRONG_BUY' | 'BUY' | 'WAIT' | 'DANGER' | 'ABORT';
export type SessionMomentum = 'cold' | 'neutral' | 'hot';

type TierPercentages = Record<CrashTier, number>;
type MarkovMatrix = Record<CrashTier, TierPercentages>;

export interface TargetLevel {
  target: number;
  hitCount: number;
  hitRate: number;
  recentHitRate: number;
  signal: 'SAFE' | 'OK' | 'RISKY' | 'RARE';
  lastHitAgo: number;
  longestGap: number;
  ev: number;
  mathProb: number;
}

export interface PatternMatch {
  patternName: string;
  occurrences: number;
  nextRoundWinRates: { target: number; hitRate: number }[];
  p90?: number;
  p80?: number;
  p50?: number;
}

export interface TimePatternMatch {
  minute: number;
  occurrences: number;
  p90: number;
  p80: number;
  p50: number;
  hitRates: { target: number; hitRate: number }[];
}

export interface SequenceMatch {
  sequence: string[];
  occurrences: number;
  pInstantNext: number;
  pSafeNext: number;
  pMedNext: number;
  pHighNext: number;
  p90: number;
  p80: number;
  p50: number;
}

export interface CrashStats {
  count: number;
  mean: number;
  median: number;
  stdDev: number;
  min: number;
  max: number;

  pUnder2: number;
  p2to5: number;
  pOver5: number;
  pInstantCrash: number;

  targets: TargetLevel[];

  p99SafeCashout: number;
  p95SafeCashout: number;
  p90SafeCashout: number;
  p80SafeCashout: number;
  p70SafeCashout: number;
  p60SafeCashout: number;
  p50SafeCashout: number;

  ema: number;

  currentLowStreak: number;
  currentHighStreak: number;
  longestLowStreak: number;

  recentMean: number;
  olderMean: number;
  trend: 'rising' | 'falling' | 'flat';

  suggestedCashout: number;
  suggestedCashoutWinRate: number;
  conservativeCashout: number;
  aggressiveCashout: number;
  cashoutReason: string;

  riskScore: number;
  riskLabel: 'LOW' | 'MEDIUM' | 'HIGH';
  confidence: number;
  volatility: 'low' | 'normal' | 'high';
  volatilityPct: number;
  q3: number;

  detectedPatterns: PatternMatch[];
  timePattern?: TimePatternMatch;
  sequenceMatch?: SequenceMatch;

  // Legacy fields retained for API/UI compatibility.
  instant_crash_risk?: number;
  instant_crash_warning?: string;
  recentOutcomes: number[];

  // Markov-chain output.
  markovMatrix: MarkovMatrix;
  markovNext: TierPercentages;
  markovSuggestedCashout: number;

  // Five-round session momentum.
  sessionDanger: boolean;
  sessionHot: boolean;
  sessionMomentum: SessionMomentum;

  // Composite decision output.
  masterSignal: MasterSignal;
  signalConfidence: number;

  // Instant-cluster model. Camel-case fields are canonical; snake-case fields
  // above remain aliases for existing callers.
  instantClusterRisk: number;
  instantCrashWarning: string;
}

export interface BetTimeData {
  isLKSleep?: boolean;
  currentLKTimeStr?: string;
  lkPhase?: 'MORNING' | 'PRIME' | 'LATE' | string;
}

export interface BetSignal {
  should_bet: boolean;
  skip_reason: string | null;
  strategy: string;
  cashout_target: number;
  recommended_bet_units: number;
  swing_target: number | null;
  volatility_phase: 'CALM' | 'NORMAL' | 'VOLATILE';
  recommended_stake_pct: number;
  strategy_reason?: string;
}

interface NormalizedRound {
  crash_point: number;
  created_at: string;
  timestamp: number;
}

const TIERS: readonly CrashTier[] = ['INSTANT', 'LOW', 'MED', 'HIGH'];
const TARGET_LEVELS = [
  1.05, 1.1, 1.18, 1.2, 1.5, 1.8, 2, 3, 5, 10, 15, 20, 25,
] as const;

const ZERO_TIERS: TierPercentages = {
  INSTANT: 0,
  LOW: 0,
  MED: 0,
  HIGH: 0,
};

const round1 = (value: number): number => Math.round(value * 10) / 10;
const round2 = (value: number): number => Math.round(value * 100) / 100;
const clamp = (value: number, min: number, max: number): number =>
  Math.min(max, Math.max(min, value));

function meanOf(values: readonly number[], fallback = 0): number {
  return values.length === 0
    ? fallback
    : values.reduce((sum, value) => sum + value, 0) / values.length;
}

function tierOf(value: number): CrashTier {
  if (value < 1.1) return 'INSTANT';
  if (value < 2) return 'LOW';
  if (value < 5) return 'MED';
  return 'HIGH';
}

function normalizeRounds(
  rawRounds: { crash_point: number; created_at: string }[],
): NormalizedRound[] {
  const seen = new Set<string>();
  const normalized: NormalizedRound[] = [];

  for (const raw of rawRounds) {
    const value = Number(raw.crash_point);
    const timestamp = Date.parse(raw.created_at);
    if (!Number.isFinite(value) || value < 1 || !Number.isFinite(timestamp)) continue;

    // Deduplicate exact double-inserts. UNIQUE(created_at, crash_point) is the
    // safest identity until round_number is surfaced in this function's input.
    const key = `${timestamp}|${value}`;
    if (seen.has(key)) continue;
    seen.add(key);

    normalized.push({
      crash_point: value,
      created_at: raw.created_at,
      timestamp,
    });
  }

  // Every recency-based calculation assumes index 0 is the latest round.
  return normalized.sort((a, b) => b.timestamp - a.timestamp);
}

function percentagesFromCounts(counts: Record<CrashTier, number>): TierPercentages {
  const total = TIERS.reduce((sum, tier) => sum + counts[tier], 0);
  if (total === 0) return { ...ZERO_TIERS };

  const result: TierPercentages = {
    INSTANT: round1((counts.INSTANT / total) * 100),
    LOW: round1((counts.LOW / total) * 100),
    MED: round1((counts.MED / total) * 100),
    HIGH: round1((counts.HIGH / total) * 100),
  };

  // Make rounded percentages total exactly 100.0.
  const sum = TIERS.reduce((acc, tier) => acc + result[tier], 0);
  const largest = TIERS.reduce((best, tier) =>
    counts[tier] > counts[best] ? tier : best,
  );
  result[largest] = round1(result[largest] + (100 - sum));
  return result;
}

function buildMarkov(values: readonly number[]): {
  matrix: MarkovMatrix;
  next: TierPercentages;
  suggestedCashout: number;
  currentStateTransitions: number;
} {
  const counts: Record<CrashTier, Record<CrashTier, number>> = {
    INSTANT: { INSTANT: 0, LOW: 0, MED: 0, HIGH: 0 },
    LOW: { INSTANT: 0, LOW: 0, MED: 0, HIGH: 0 },
    MED: { INSTANT: 0, LOW: 0, MED: 0, HIGH: 0 },
    HIGH: { INSTANT: 0, LOW: 0, MED: 0, HIGH: 0 },
  };
  const globalCounts: Record<CrashTier, number> = { ...ZERO_TIERS };
  const chronological = [...values].reverse();

  for (const value of chronological) globalCounts[tierOf(value)] += 1;
  for (let index = 0; index < chronological.length - 1; index += 1) {
    counts[tierOf(chronological[index])][tierOf(chronological[index + 1])] += 1;
  }

  const fallback = percentagesFromCounts(globalCounts);
  const matrix = {} as MarkovMatrix;
  for (const from of TIERS) {
    const rowTotal = TIERS.reduce((sum, to) => sum + counts[from][to], 0);
    matrix[from] = rowTotal > 0 ? percentagesFromCounts(counts[from]) : { ...fallback };
  }

  const currentTier = values.length > 0 ? tierOf(values[0]) : 'LOW';
  const next = { ...matrix[currentTier] };
  const currentStateTransitions = TIERS.reduce(
    (sum, to) => sum + counts[currentTier][to],
    0,
  );
  const mostLikely = TIERS.reduce((best, tier) =>
    next[tier] > next[best] ? tier : best,
  );
  const cashouts: Record<CrashTier, number> = {
    INSTANT: 1.05,
    LOW: 1.25,
    MED: 2,
    HIGH: 3,
  };

  return {
    matrix,
    next,
    suggestedCashout: cashouts[mostLikely],
    currentStateTransitions,
  };
}

function cashoutAtWinRate(
  sortedAscending: readonly number[],
  targetPercent: number,
): number {
  if (sortedAscending.length === 0) return 1.05;
  const quantile = clamp(1 - targetPercent / 100, 0, 1);
  const index = Math.floor(quantile * (sortedAscending.length - 1));
  return round2(sortedAscending[index]);
}

function percentileFromOutcomes(
  outcomes: readonly number[],
  targetPercent: number,
): number {
  return clamp(
    cashoutAtWinRate([...outcomes].sort((a, b) => a - b), targetPercent),
    1.01,
    30,
  );
}

function countLeading(values: readonly number[], predicate: (value: number) => boolean): number {
  let count = 0;
  for (const value of values) {
    if (!predicate(value)) break;
    count += 1;
  }
  return count;
}

function longestRun(values: readonly number[], predicate: (value: number) => boolean): number {
  let longest = 0;
  let current = 0;
  for (const value of [...values].reverse()) {
    if (predicate(value)) {
      current += 1;
      longest = Math.max(longest, current);
    } else {
      current = 0;
    }
  }
  return longest;
}

function recencyWeight(index: number): number {
  if (index < 5) return 3;
  if (index < 15) return 1;
  if (index < 30) return 1.5;
  return 1;
}

function tierRisk(value: number): number {
  const tier = tierOf(value);
  if (tier === 'INSTANT') return 100;
  if (tier === 'LOW') return 68;
  if (tier === 'MED') return 28;
  return 8;
}

function computeInstantClusterRisk(values: readonly number[]): number {
  if (values.length === 0) return 0;

  let clusterWindows = 0;
  let windows = 0;
  for (let start = 0; start + 5 <= values.length; start += 1) {
    windows += 1;
    const instantCount = values
      .slice(start, start + 5)
      .filter((value) => tierOf(value) === 'INSTANT').length;
    if (instantCount >= 2) clusterWindows += 1;
  }

  const historicalRate = windows > 0
    ? (clusterWindows / windows) * 100
    : (values.filter((value) => tierOf(value) === 'INSTANT').length / values.length) * 100;
  const recentInstantCount = values
    .slice(0, 5)
    .filter((value) => tierOf(value) === 'INSTANT').length;
  const recentPressure = clamp((recentInstantCount / 2) * 100, 0, 100);

  let risk = historicalRate * 0.7 + recentPressure * 0.3;
  if (tierOf(values[0]) === 'INSTANT') risk *= 2;
  return Math.round(clamp(risk, 0, 100));
}

function analyzeSequence(values: readonly number[]): SequenceMatch | undefined {
  if (values.length < 5) return undefined;

  for (let length = 4; length >= 2; length -= 1) {
    const current = values.slice(0, length).reverse().map(tierOf);
    const outcomes: number[] = [];

    for (let nextIndex = 1; nextIndex + length <= values.length; nextIndex += 1) {
      const historical = values
        .slice(nextIndex, nextIndex + length)
        .reverse()
        .map(tierOf);
      if (historical.every((tier, index) => tier === current[index])) {
        outcomes.push(values[nextIndex - 1]);
      }
    }

    if (outcomes.length > 0) {
      return {
        sequence: current,
        occurrences: outcomes.length,
        pInstantNext: Math.round(
          (outcomes.filter((value) => tierOf(value) === 'INSTANT').length / outcomes.length) * 100,
        ),
        pSafeNext: Math.round(
          (outcomes.filter((value) => value >= 1.15).length / outcomes.length) * 100,
        ),
        pMedNext: Math.round(
          (outcomes.filter((value) => value >= 2).length / outcomes.length) * 100,
        ),
        pHighNext: Math.round(
          (outcomes.filter((value) => value >= 5).length / outcomes.length) * 100,
        ),
        p90: percentileFromOutcomes(outcomes, 90),
        p80: percentileFromOutcomes(outcomes, 80),
        p50: percentileFromOutcomes(outcomes, 50),
      };
    }
  }

  return undefined;
}

function analyzeCurrentStreak(
  values: readonly number[],
  streakLength: number,
  kind: 'low' | 'high',
): PatternMatch | undefined {
  if (streakLength === 0) return undefined;
  const matches = (value: number): boolean => kind === 'low' ? value < 2 : value >= 2;
  const outcomes: number[] = [];

  for (let nextIndex = 0; nextIndex + streakLength < values.length; nextIndex += 1) {
    let matched = true;
    for (let offset = 1; offset <= streakLength; offset += 1) {
      if (!matches(values[nextIndex + offset])) {
        matched = false;
        break;
      }
    }
    if (matched) outcomes.push(values[nextIndex]);
  }

  if (outcomes.length === 0) return undefined;
  const targetLevels = [1.2, 1.5, 2, 3, 5];
  return {
    patternName: `${streakLength} consecutive ${kind} crashes`,
    occurrences: outcomes.length,
    nextRoundWinRates: targetLevels.map((target) => ({
      target,
      hitRate: Math.round(
        (outcomes.filter((outcome) => outcome >= target).length / outcomes.length) * 100,
      ),
    })),
    p90: percentileFromOutcomes(outcomes, 90),
    p80: percentileFromOutcomes(outcomes, 80),
    p50: percentileFromOutcomes(outcomes, 50),
  };
}

function analyzeMinutePattern(rounds: readonly NormalizedRound[]): TimePatternMatch | undefined {
  if (rounds.length === 0) return undefined;
  const minute = new Date(rounds[0].timestamp).getUTCMinutes();
  const outcomes = rounds
    .filter((round) => new Date(round.timestamp).getUTCMinutes() === minute)
    .map((round) => round.crash_point);
  if (outcomes.length < 10) return undefined;

  return {
    minute,
    occurrences: outcomes.length,
    p90: percentileFromOutcomes(outcomes, 90),
    p80: percentileFromOutcomes(outcomes, 80),
    p50: percentileFromOutcomes(outcomes, 50),
    hitRates: [1.2, 1.5, 2, 3, 5].map((target) => ({
      target,
      hitRate: Math.round(
        (outcomes.filter((outcome) => outcome >= target).length / outcomes.length) * 100,
      ),
    })),
  };
}

export function computeStats(
  rawRounds: { crash_point: number; created_at: string }[],
): CrashStats {
  const rounds = normalizeRounds(rawRounds);
  if (rounds.length === 0) return emptyStats();

  const values = rounds.map((round) => round.crash_point);
  const sorted = [...values].sort((a, b) => a - b);
  const n = values.length;
  const mean = meanOf(values);
  const median = n % 2 === 0
    ? (sorted[n / 2 - 1] + sorted[n / 2]) / 2
    : sorted[Math.floor(n / 2)];
  const variance = meanOf(values.map((value) => (value - mean) ** 2));
  const stdDev = Math.sqrt(variance);
  const min = sorted[0];
  const max = sorted[n - 1];

  const pUnder2 = Math.round((values.filter((value) => value < 2).length / n) * 100);
  const p2to5 = Math.round(
    (values.filter((value) => value >= 2 && value < 5).length / n) * 100,
  );
  const pOver5 = Math.round((values.filter((value) => value >= 5).length / n) * 100);
  const pInstantCrash = round1(
    (values.filter((value) => value < 1.1).length / n) * 100,
  );

  const recent20 = values.slice(0, 20);
  const targets: TargetLevel[] = TARGET_LEVELS.map((target) => {
    const hitCount = values.filter((value) => value >= target).length;
    const hitRate = Math.round((hitCount / n) * 100);
    const recentHitRate = Math.round(
      (recent20.filter((value) => value >= target).length / recent20.length) * 100,
    );
    const lastHitAgo = values.findIndex((value) => value >= target);

    let longestGap = 0;
    let gap = 0;
    for (const value of [...values].reverse()) {
      if (value >= target) {
        longestGap = Math.max(longestGap, gap);
        gap = 0;
      } else {
        gap += 1;
      }
    }
    longestGap = Math.max(longestGap, gap);

    let signal: TargetLevel['signal'];
    if (hitRate >= 80) signal = 'SAFE';
    else if (hitRate >= 55) signal = 'OK';
    else if (hitRate >= 25) signal = 'RISKY';
    else signal = 'RARE';

    return {
      target,
      hitCount,
      hitRate,
      recentHitRate,
      signal,
      lastHitAgo,
      longestGap,
      ev: round2((hitRate / 100) * target - 1),
      mathProb: round1((0.97 / target) * 100),
    };
  });

  const p99SafeCashout = cashoutAtWinRate(sorted, 99);
  const p95SafeCashout = cashoutAtWinRate(sorted, 95);
  const p90SafeCashout = cashoutAtWinRate(sorted, 90);
  const p80SafeCashout = cashoutAtWinRate(sorted, 80);
  const p70SafeCashout = cashoutAtWinRate(sorted, 70);
  const p60SafeCashout = cashoutAtWinRate(sorted, 60);
  const p50SafeCashout = round2(median);

  const chronological = [...values].reverse();
  const span = Math.min(20, n);
  const alpha = 2 / (span + 1);
  let ema = chronological[0];
  for (let index = 1; index < chronological.length; index += 1) {
    ema = alpha * chronological[index] + (1 - alpha) * ema;
  }
  ema = round2(ema);

  const currentLowStreak = countLeading(values, (value) => value < 2);
  const currentHighStreak = countLeading(values, (value) => value >= 2);
  const currentInstantStreak = countLeading(values, (value) => tierOf(value) === 'INSTANT');
  const longestLowStreak = longestRun(values, (value) => value < 2);

  const recent = values.slice(0, 5);
  const older = values.slice(5, 15);
  const recentMean = meanOf(recent, mean);
  const olderMean = meanOf(older, mean);
  let trend: CrashStats['trend'] = 'flat';
  if (recentMean > olderMean * 1.2) trend = 'rising';
  else if (recentMean < olderMean * 0.8) trend = 'falling';

  const cvRatio = mean > 0 ? stdDev / mean : 0;
  const volatilityPct = round1(cvRatio * 100);
  const q3 = sorted[Math.min(n - 1, Math.floor((n - 1) * 0.75))];
  let volatility: CrashStats['volatility'] = 'normal';
  if (cvRatio > 1.2) volatility = 'high';
  else if (cvRatio < 0.5) volatility = 'low';

  const momentumWindow = values.slice(0, 5);
  const coldCount = momentumWindow.filter((value) => value < 2).length;
  const hotCount = momentumWindow.filter((value) => value >= 2).length;
  const sessionDanger = momentumWindow.length >= 3 && coldCount >= 3;
  const sessionHot = momentumWindow.length >= 3 && hotCount >= 3;
  const sessionMomentum: SessionMomentum = sessionDanger
    ? 'cold'
    : sessionHot
      ? 'hot'
      : 'neutral';

  // Weighted recency risk: rounds 0-4 => 3x, 5-14 => 1x, 15-29 => 1.5x, 30+ => 1x.
  let weightedRiskTotal = 0;
  let totalWeight = 0;
  values.forEach((value, index) => {
    const weight = recencyWeight(index);
    weightedRiskTotal += tierRisk(value) * weight;
    totalWeight += weight;
  });
  let riskScore = totalWeight > 0 ? weightedRiskTotal / totalWeight : 50;
  if (sessionDanger) riskScore += 25;
  if (sessionHot) riskScore -= 15;
  if (trend === 'falling') riskScore += 5;
  if (trend === 'rising') riskScore -= 5;
  if (currentInstantStreak >= 2) riskScore += 10;
  riskScore = Math.round(clamp(riskScore, 0, 100));

  const riskLabel: CrashStats['riskLabel'] = riskScore >= 60
    ? 'HIGH'
    : riskScore >= 35
      ? 'MEDIUM'
      : 'LOW';

  const markov = buildMarkov(values);
  const favorableMarkov = markov.next.MED + markov.next.HIGH;
  let masterSignal: MasterSignal;
  if (riskScore >= 80 || currentInstantStreak >= 3) {
    masterSignal = 'ABORT';
  } else if (riskScore >= 60 || sessionDanger) {
    masterSignal = 'DANGER';
  } else if (riskScore >= 40) {
    masterSignal = 'WAIT';
  } else if (riskScore < 25 && sessionHot && favorableMarkov >= 60) {
    masterSignal = 'STRONG_BUY';
  } else {
    masterSignal = 'BUY';
  }

  const instantClusterRisk = computeInstantClusterRisk(values);
  const instantCrashWarning = instantClusterRisk > 60
    ? `High instant-crash cluster risk (${instantClusterRisk}%): avoid aggressive targets.`
    : 'No elevated instant-crash cluster detected.';

  const sampleStrength = clamp(Math.sqrt(n / 200) * 100, 0, 100);
  const markovDominance = Math.max(...TIERS.map((tier) => markov.next[tier]));
  const transitionStrength = clamp(
    Math.sqrt(markov.currentStateTransitions / 30) * 100,
    0,
    100,
  );
  const momentumStrength = momentumWindow.length < 5
    ? (momentumWindow.length / 5) * 50
    : Math.abs(hotCount - coldCount) * 20;
  const signalConfidence = Math.round(clamp(
    sampleStrength * 0.45
      + markovDominance * 0.2
      + transitionStrength * 0.25
      + momentumStrength * 0.1,
    0,
    100,
  ));
  const confidence = Math.min(100, Math.round((n / 50) * 100));

  const winRateAt = (target: number): number =>
    Math.round((values.filter((value) => value >= target).length / n) * 100);

  let suggestedCashout = p70SafeCashout;
  const cashoutReasons = [`${round2(p70SafeCashout)}x base from the 70% historical cashout percentile`];
  const markovLeader = TIERS.reduce((best, tier) =>
    markov.next[tier] > markov.next[best] ? tier : best,
  );

  if (sessionHot && markovLeader === 'MED') {
    suggestedCashout = Math.max(
      suggestedCashout,
      Math.min(markov.suggestedCashout, suggestedCashout * 1.15),
    );
    cashoutReasons.push('raised for hot momentum and a MED Markov lead');
  }
  if (sessionDanger || riskScore > 60) {
    suggestedCashout = Math.min(suggestedCashout, p80SafeCashout);
    cashoutReasons.push('lowered for session danger or elevated weighted risk');
  }
  if (masterSignal === 'ABORT') {
    suggestedCashout = Math.min(suggestedCashout, 3);
    cashoutReasons.push('capped at 3.00x by ABORT');
  }
  suggestedCashout = round2(clamp(suggestedCashout, 1.05, 30));

  const conservativeCashout = round2(Math.max(1.05, p90SafeCashout));
  const aggressiveCashout = round2(Math.max(1.5, p50SafeCashout));
  const sequenceMatch = analyzeSequence(values);
  const detectedPatterns: PatternMatch[] = [];
  const lowPattern = analyzeCurrentStreak(values, currentLowStreak, 'low');
  const highPattern = analyzeCurrentStreak(values, currentHighStreak, 'high');
  if (lowPattern) detectedPatterns.push(lowPattern);
  if (highPattern) detectedPatterns.push(highPattern);
  const timePattern = analyzeMinutePattern(rounds);

  return {
    count: n,
    mean: round2(mean),
    median: round2(median),
    stdDev: round2(stdDev),
    min: round2(min),
    max: round2(max),
    pUnder2,
    p2to5,
    pOver5,
    pInstantCrash,
    targets,
    p99SafeCashout,
    p95SafeCashout,
    p90SafeCashout,
    p80SafeCashout,
    p70SafeCashout,
    p60SafeCashout,
    p50SafeCashout,
    ema,
    currentLowStreak,
    currentHighStreak,
    longestLowStreak,
    recentMean: round2(recentMean),
    olderMean: round2(olderMean),
    trend,
    suggestedCashout,
    suggestedCashoutWinRate: winRateAt(suggestedCashout),
    conservativeCashout,
    aggressiveCashout,
    cashoutReason: `${cashoutReasons.join('; ')}. Final target: ${suggestedCashout.toFixed(2)}x.`,
    riskScore,
    riskLabel,
    confidence,
    volatility,
    volatilityPct,
    q3: round2(q3),
    detectedPatterns,
    ...(timePattern ? { timePattern } : {}),
    ...(sequenceMatch ? { sequenceMatch } : {}),
    instant_crash_risk: instantClusterRisk,
    instant_crash_warning: instantCrashWarning,
    recentOutcomes: values.slice(0, 10),
    markovMatrix: markov.matrix,
    markovNext: markov.next,
    markovSuggestedCashout: markov.suggestedCashout,
    sessionDanger,
    sessionHot,
    sessionMomentum,
    masterSignal,
    signalConfidence,
    instantClusterRisk,
    instantCrashWarning,
  };
}

function emptyStats(): CrashStats {
  const emptyTargets: TargetLevel[] = TARGET_LEVELS.map((target) => ({
    target,
    hitCount: 0,
    hitRate: 0,
    recentHitRate: 0,
    signal: 'RARE',
    lastHitAgo: -1,
    longestGap: 0,
    ev: -1,
    mathProb: round1((0.97 / target) * 100),
  }));
  const zeroMatrix: MarkovMatrix = {
    INSTANT: { ...ZERO_TIERS },
    LOW: { ...ZERO_TIERS },
    MED: { ...ZERO_TIERS },
    HIGH: { ...ZERO_TIERS },
  };

  return {
    count: 0,
    mean: 0,
    median: 0,
    stdDev: 0,
    min: 0,
    max: 0,
    pUnder2: 0,
    p2to5: 0,
    pOver5: 0,
    pInstantCrash: 0,
    targets: emptyTargets,
    p99SafeCashout: 1.05,
    p95SafeCashout: 1.05,
    p90SafeCashout: 1.1,
    p80SafeCashout: 1.2,
    p70SafeCashout: 1.5,
    p60SafeCashout: 1.8,
    p50SafeCashout: 2,
    ema: 0,
    currentLowStreak: 0,
    currentHighStreak: 0,
    longestLowStreak: 0,
    recentMean: 0,
    olderMean: 0,
    trend: 'flat',
    suggestedCashout: 1.05,
    suggestedCashoutWinRate: 0,
    conservativeCashout: 1.1,
    aggressiveCashout: 1.5,
    cashoutReason: 'No valid rounds are available; using the 1.05x safety floor.',
    riskScore: 50,
    riskLabel: 'MEDIUM',
    confidence: 0,
    volatility: 'normal',
    volatilityPct: 0,
    q3: 0,
    detectedPatterns: [],
    instant_crash_risk: 0,
    instant_crash_warning: 'Insufficient data.',
    recentOutcomes: [],
    markovMatrix: zeroMatrix,
    markovNext: { ...ZERO_TIERS },
    markovSuggestedCashout: 1.05,
    sessionDanger: false,
    sessionHot: false,
    sessionMomentum: 'neutral',
    masterSignal: 'WAIT',
    signalConfidence: 0,
    instantClusterRisk: 0,
    instantCrashWarning: 'Insufficient data.',
  };
}

/** Grade whether the recommended cashout or fallback risk classification matched. */
export function gradePrediction(
  risk: 'LOW' | 'MEDIUM' | 'HIGH',
  actualCrash: number,
  cashoutTarget?: number | null,
): boolean {
  if (cashoutTarget !== null && cashoutTarget !== undefined && cashoutTarget > 1) {
    return actualCrash >= cashoutTarget;
  }
  if (risk === 'LOW') return actualCrash >= 2;
  if (risk === 'MEDIUM') return actualCrash >= 1.5 && actualCrash < 4;
  return actualCrash < 1.5;
}

export function computeBetSignal(
  stats: CrashStats,
  gameType: '1xbet' | 'aviator' | 'luckyjet' = '1xbet',
  timeData?: BetTimeData,
): BetSignal {
  let volatility_phase: BetSignal['volatility_phase'] = 'NORMAL';
  if (stats.stdDev < 1.5) volatility_phase = 'CALM';
  else if (stats.stdDev > 3.5) volatility_phase = 'VOLATILE';

  const skipReasons: string[] = [];
  if (timeData?.isLKSleep) {
    skipReasons.push(`Sri Lanka sleep phase${timeData.currentLKTimeStr ? ` (${timeData.currentLKTimeStr})` : ''}`);
  }
  if (stats.masterSignal === 'ABORT') skipReasons.push('Composite signal is ABORT');
  else if (stats.masterSignal === 'DANGER') skipReasons.push('Composite signal is DANGER');
  if (stats.instantClusterRisk > 60) {
    skipReasons.push(`Instant-crash cluster risk is ${stats.instantClusterRisk}%`);
  }

  if (skipReasons.length > 0) {
    return {
      should_bet: false,
      skip_reason: skipReasons.join(' | '),
      strategy: 'SKIP',
      cashout_target: 0,
      recommended_bet_units: 0,
      swing_target: null,
      volatility_phase,
      recommended_stake_pct: 0,
      strategy_reason: stats.cashoutReason,
    };
  }

  const limits: Record<'1xbet' | 'aviator' | 'luckyjet', { min: number; max: number }> = {
    '1xbet': { min: 1.1, max: 3 },
    aviator: { min: 1.15, max: 2.5 },
    luckyjet: { min: 1.08, max: 2.75 },
  };
  const limit = limits[gameType];
  let cashoutTarget = clamp(stats.suggestedCashout, limit.min, limit.max);
  if (timeData?.lkPhase !== 'PRIME') cashoutTarget = Math.min(cashoutTarget, 1.2);
  cashoutTarget = round2(cashoutTarget);

  const aggressive = stats.masterSignal === 'STRONG_BUY';
  const stake = aggressive ? 3 : stats.masterSignal === 'BUY' ? 2 : 1;

  return {
    should_bet: true,
    skip_reason: null,
    strategy: aggressive ? 'AGGRESSIVE' : 'CONSERVATIVE',
    cashout_target: cashoutTarget,
    recommended_bet_units: aggressive ? 1.5 : 1,
    swing_target: aggressive ? round2(Math.min(stats.aggressiveCashout, limit.max)) : null,
    volatility_phase,
    recommended_stake_pct: volatility_phase === 'VOLATILE' ? Math.min(1, stake) : stake,
    strategy_reason: `${stats.masterSignal} at ${stats.signalConfidence}% confidence. ${stats.cashoutReason}`,
  };
}

export function buildHumanSummary(
  stats: CrashStats,
  betSignal: ReturnType<typeof computeBetSignal>,
): string {
  if (!betSignal.should_bet) {
    return `${stats.masterSignal}: ${betSignal.skip_reason ?? 'risk controls blocked entry'}. ${stats.instantCrashWarning}`;
  }

  const favorableMarkov = round1(stats.markovNext.MED + stats.markovNext.HIGH);
  return `${stats.masterSignal} (${stats.signalConfidence}% confidence): ${stats.sessionMomentum} momentum, ${stats.riskScore}/100 weighted risk, and ${favorableMarkov}% Markov probability of MED/HIGH next. Target ${betSignal.cashout_target.toFixed(2)}x with ${betSignal.recommended_stake_pct}% bankroll exposure.`;
}
